# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            "Marco Fargetta's blog"
tagline:          ''
description:      'My personal blog using Jekyll Metro'
url:              'http://fmarco76.github.io'
#url:              'http://localhost:4000'

# Author Details
author:         'Marco Fargetta'
#linkedin:       'https://ae.linkedin.com/in/olakara/'
#twitter:        'https://twitter.com/olakara'
#facebook:       'https://www.facebook.com/olakara'
#gplus:          'https://plus.google.com/100425464897246255887/'

# Google Analytics
gahandler: 'UA-51273549-1'

# Blog Configurations
paginate: 2 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.7.1
